// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_QHbedZdaeGCYuGm78ZKpJu8sB-4RW2E',
    appId: '1:271656103984:web:c9a6cbe6171b46f2e4bdf5',
    messagingSenderId: '271656103984',
    projectId: 'push-notifications-5c68c',
    authDomain: 'push-notifications-5c68c.firebaseapp.com',
    storageBucket: 'push-notifications-5c68c.appspot.com',
    measurementId: 'G-VTMJMJ0CKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN8_d4L-oJ_i2TqTeOyN35r6zKTj1-4k4',
    appId: '1:271656103984:android:850d0db13d7070ede4bdf5',
    messagingSenderId: '271656103984',
    projectId: 'push-notifications-5c68c',
    storageBucket: 'push-notifications-5c68c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOmW19UiSRng5wVhaw_nD4FPDVbSuzE7E',
    appId: '1:271656103984:ios:5786204501080216e4bdf5',
    messagingSenderId: '271656103984',
    projectId: 'push-notifications-5c68c',
    storageBucket: 'push-notifications-5c68c.appspot.com',
    iosBundleId: 'com.example.bikeFixupTeamProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOmW19UiSRng5wVhaw_nD4FPDVbSuzE7E',
    appId: '1:271656103984:ios:1df9572d5445f293e4bdf5',
    messagingSenderId: '271656103984',
    projectId: 'push-notifications-5c68c',
    storageBucket: 'push-notifications-5c68c.appspot.com',
    iosBundleId: 'com.example.bikeFixupTeamProject.RunnerTests',
  );
}
